openapi: 3.0.3
info:
  title: Bodegas API
  version: '1.0'
paths:
  /v1/bodegas:
    get:
      summary: Listar bodegas
      parameters:
        - in: query
          name: q
          schema:
            type: string
        - in: query
          name: sort
          schema:
            type: string
      responses:
        '200':
          description: Lista paginada de bodegas
    post:
      summary: Crear bodega
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BodegaInput'
      responses:
        '201':
          description: Bodega creada
  /v1/bodegas/{id}:
    get:
      summary: Obtener bodega
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Bodega
        '404':
          description: No encontrada
    put:
      summary: Actualizar bodega
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BodegaInput'
      responses:
        '200':
          description: Bodega actualizada
    delete:
      summary: Eliminar bodega
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Eliminada
components:
  schemas:
    Bodega:
      type: object
      properties:
        id:
          type: integer
        local_id:
          type: integer
        nombre:
          type: string
        es_principal:
          type: boolean
    BodegaInput:
      type: object
      required: [local_id, nombre, es_principal]
      properties:
        local_id:
          type: integer
        nombre:
          type: string
        es_principal:
          type: boolean
